version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"  # Map the application's port to a host port if needed
    volumes:
      - .:/app      # Mount the current directory into the container for development (optional)
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres     # Add other services your app depends on (e.g., RabbitMQ)

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: dddtasks
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"  # Map the PostgreSQL port to a host port (optional)
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
